export default {
    ethereum: { chainId: 1, name: 'Ethereum Mainnet' },
    polygon: { chainId: 137, name: 'Polygon' },
    arbitrum: { chainId: 42161, name: 'Arbitrum One' },
    optimism: { chainId: 10, name: 'Optimism' },
    base: { chainId: 8453, name: 'Base' },
    avalanche: { chainId: 43114, name: 'Avalanche C-Chain' },
    bsc: { chainId: 56, name: 'BNB Smart Chain' },
    gnosis: { chainId: 100, name: 'Gnosis' },
    fantom: { chainId: 250, name: 'Fantom' },
    linea: { chainId: 59144, name: 'Linea' },
    zksync: { chainId: 324, name: 'zkSync Era' },
    scroll: { chainId: 534352, name: 'Scroll' },
    berachain: { chainId: 80094, name: 'Berachain' },
    sonic: { chainId: 146, name: 'Sonic' },
    zircuit: { chainId: 48900, name: 'Zircuit' },
    core: { chainId: 1116, name: 'Core Blockchain' },
    unichain: { chainId: 130, name: 'Unichain' },
    cronos: { chainId: 25, name: 'Cronos' },
    sei: { chainId: 1329, name: 'Sei Network' },
    bitlayer: { chainId: 200901, name: 'Bitlayer' },
    abstract: { chainId: 2741, name: 'Abstract' },
};
